# Generated by Django 4.0 on 2023-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('setprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image1', models.ImageField(blank=True, upload_to='book_images/')),
                ('image2', models.ImageField(blank=True, upload_to='book_images/')),
                ('image3', models.ImageField(blank=True, upload_to='book_images/')),
                ('image4', models.ImageField(blank=True, upload_to='book_images/')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=255)),

            ],
        ),
    ]
