# Generated by Django 4.0 on 2023-10-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitabApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellBook',
            new_name='SellBook1',
        ),
    ]
