# Generated by Django 4.0 on 2023-10-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabApp', '0002_rename_sellbook_sellbook1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbook1',
            name='slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
