# Generated by Django 4.0 on 2023-10-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitabApp', '0003_sellbook1_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellbook1',
            name='slug',
        ),
    ]
