# Generated by Django 4.0 on 2023-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabApp', '0004_remove_sellbook1_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellbook1',
            name='setprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
