# Generated by Django 4.0 on 2024-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabApp', '0006_sellbook1_authorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
